### ISSUE TITLE
Screen LCD

### ISSUE THREAD

**Issue by fschatbot** [circuitdiagram/components#170]
Here is the YAML Definition I was able to cook up!
```yaml
kind: ComponentConfiguration/v1
metadata:
  guid: a6da97ce-f923-499f-8c62-82251ef3606a
  name: LCD Configuration
  version:
  description:
template:
  name: Integrated Circuit 2
  guid: 2cd49d7c-eb1a-4fe4-9104-c45023e3fc95
properties:
  - name: Header
    value: LCD
  - name: Size
    value: 16
  - name: Pin0
    value: LED-
  - name: Pin1
    value: LED+
  - name: Pin2
    value: DB7
  - name: Pin3
    value: DB6
  - name: Pin4
    value: DB5
  - name: Pin5
    value: DB4
  - name: Pin6
    value: DB3
  - name: Pin7
    value: DB2
  - name: Pin8
    value: DB1
  - name: Pin9
    value: DB0
  - name: Pin10
    value: E
  - name: Pin11
    value: R/W
  - name: Pin12
    value: RS
  - name: Pin13
    value: V0
  - name: Pin14
    value: VDD
  - name: Pin15
    value: VSS
```
