### ISSUE TITLE
Several USB Connectors (and Breakouts)

### ISSUE THREAD

**Issue by Chaos02** [circuitdiagram/components#247]
Hi - I'll be slowly filling this thread with several different USB Breakouts

Starting with:
<details>
  <summary>USB-C</summary>

### Connector

  <details>
    <summary>yaml</summary>

```yaml
kind: ComponentConfiguration/v1
metadata:
  guid: 33923b78-254b-4fe0-9dad-e3cf406b6dc5
  name: Untitled Configuration
  version: 
  description: 
template:
  name: Integrated Circuit 2
  guid: 2cd49d7c-eb1a-4fe4-9104-c45023e3fc95
properties:
- name: Header
  value: USB-C Breakout
- name: Size
  value: 28
- name: Pin0
  value: USB-C Male/Female
- name: Pin4
  value: B1
- name: Pin5
  value: A1
- name: Pin6
  value: B2
- name: Pin7
  value: A2
- name: Pin8
  value: B3
- name: Pin9
  value: A3
- name: Pin10
  value: B4
- name: Pin11
  value: A4
- name: Pin12
  value: B5
- name: Pin13
  value: A5
- name: Pin14
  value: B6
- name: Pin15
  value: A6
- name: Pin16
  value: B7
- name: Pin17
  value: A7
- name: Pin18
  value: B8
- name: Pin19
  value: A8
- name: Pin20
  value: B9
- name: Pin21
  value: A9
- name: Pin22
  value: B10
- name: Pin23
  value: A10
- name: Pin24
  value: B11
- name: Pin25
  value: A11
- name: Pin26
  value: B12
- name: Pin27
  value: A12

```

  </details>
</details>
